codelists/: Add buyer-contracting-type and Directive 2014/25/EU codes…
open-contracting-extensions/ocds_organizationClassification_extension pull request #4
Opened 2023-04-05 15:26 UTC by odscjen

… to +itemClassificationScheme.csv

Based on 1.2 branch rather than the 1.1 branch.

2 errors still come up, a complaint about properties within properties (which seems to affect quite a few extensions) and one of the new codes doesn't match the code pattern.

2023-04-10 23:45 UTC, duncandewhurst requested changes
I made a few suggestions, but I think we may want to revisit the mapping of BT-10:

> - [Get the organization for the buyer](operations.md#get-the-organization-for-the-buyer) and add a `Classification` object to its `.details.classifications` array.
> - Map the value of this field to the classification's `.id`.
> - Look up the code's label in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/main-activity) and map it to the classification's `.description`.
> - If the code's definition in the authority table includes ["COFOG"](<https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Classification_of_the_functions_of_government_(COFOG)>), set the classification's `.scheme` to 'COFOG'. Otherwise, set it to 'Directive 2014/25/EU'.

As written, the mapping would lead to classifications like:

```json
{
  "scheme": "COFOG",
  "id": "defence"
}
```

However, 'defence' is not a code from COFOG. It is the description of [code '02'](https://unstats.un.org/unsd/classifications/Econ/Structure/Detail/EN/4/02) (the relationship between codes and descriptions is a clearer in the [COFOG text file](https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/COFOG_english_structure.txt)).

I think the options are either to add a step to the mapping to look up the COFOG code for the labels in the authority table or to add a classification scheme code for the main activity vocabulary and to explain the relationship between the vocabulary and COFOG in the code's description.

I'm also unsure about adding 'Directive 2014/25/EU' to the classification scheme codelist, since the codes in the authority table do not appear exactly in the directive, e.g. the authority table has 'gas-heat' but the article name in the directive is 'Gas and heat'. If we do add it to the classification scheme codelist, I think the description should better explain the [relationship between the codes and the directive](https://github.com/open-contracting/european-union-support/issues/64#issuecomment-939540300).

@jpmckinney what do you think?

2023-04-10 23:45 UTC, duncandewhurst commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BT-10 (Activity Authority). BT-610 (Activity Entity), and BT-740 (Buyer Contracting Entity)](https://docs.ted.europa.eu/eforms/lat
I don't think we should remove the reference to OCDS for the European since this extension is still relevant in that context.

2023-04-10 23:45 UTC, duncandewhurst commented on codelists/+itemClassificationScheme.csv
> +buyer-contracting-type,EC Buyer entity contracting type,Whether or not the buyer is a contracting entity within the domain of public procurement according to legislation of the European Parliament.,h
```suggestion
buyer-contracting-type,EC Buyer contracting entity type,Whether or not the buyer is a contracting entity within the domain of public procurement according to legislation of the European Parliament.,https://docs.ted.europa.eu/eforms/latest/reference/code-lists/buyer-contracting-type.html,organization
```

2023-04-10 23:45 UTC, duncandewhurst commented on codelists/+itemClassificationScheme.csv
> +Directive 2014/25/EU,EC Main activity concept of contracting entity,The main activities of the buyers and contracting entities within the domain of public procurement according to legistlation of the
```suggestion
Directive 2014/25/EU,EC Main activity concept of contracting entity,The main activities of the buyers and contracting entities within the domain of public procurement according to legislation of the European Parliament.,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32014L0025#d1e2854-243-1,organization
```

2023-04-12 22:27 UTC, jpmckinney commented
The EU profile uses the numeric COFOG codes, so we should use them here as well.

I agree that instead of naming the scheme 'Directive 2014/25/EU', we should probably base it on the authority table.

2023-04-13 02:43 UTC, duncandewhurst commented
Thanks! Double-checking that we're all on the same page:

If BT-610-Procedure-Buyer contains a code from the authority table that is also a description of a code from COFOG, the OCDS data will look like this:

```json
"classifications": [
  {
    "scheme": "COFOG",
    "id": "02",
    "description": "Defence"
  }
]
```

If BT-610-Procedure-Buyer contains a code from the authority table that isn't the description of a code from COFOG, the OCDS data will look like this:

```json
"classifications": [
  {
    "scheme": "main-activity",
    "id": "gas-heat",
    "description": "Production, transport or distribution of gas or heat"
  }
]
```

The new code in the classification scheme codelist will look like this:

| Code | Title | Description | Source | 
| -- | -- | -- | -- |
| main-activity | EU main activity authority list | The main activity of the contracting entity according to legislation of the European Parliament. | https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/main-activity |

I'm wondering whether

1. The description of `main-activity` in the classification scheme codelist should include some explanation of the relationship to COFOG and/or guidance on when to use codes from COFOG and when to use codes from the authority table?
1. When the code is shared with COFOG, `classifications` should have both the COFOG code and the authority table code?

```json
"classifications": [
  {
    "scheme": "COFOG",
    "id": "02",
    "description": "Defence"
  },
  {
    "scheme": "main-activity",
    "id": "defence",
    "description": "Defence"
  }
]
```

2023-04-13 18:46 UTC, jpmckinney commented
Similar to https://github.com/open-contracting-extensions/ocds_procurementMethodRationaleClassifications_extension/pull/3/files/3d862430135fe451c4a9ac01d036735abf99af0c#r1164721585 we probably want to edit the `TED_CE_ACTIVITY` title and description, so that it's clear that these two codelists have the same semantics, but different codes.

For (2), it's allowed to have entries for both main-activity and COFOG - it's common for classifications to overlap in semantics, e.g. CPV, UNSPSC, etc. As such, we don't need any special instructions on when to use one or the other. For the profile, we just want COFOG at a minimum (as it's the more international classification).

2023-04-13 18:48 UTC, jpmckinney commented
Also, for eForms codelists (across all extension updates), I think we should namespace the schemes with `eu-*`, so that the EU doesn't get to claim "main-activity".

2023-04-17 22:40 UTC, duncandewhurst commented
All sounds good. For (2), I meant should we update the mapping of BT-10 to add both the COFOG and (eu-)main-activity codes to `classifications` when the main-activity code is a COFOG description? As it stands, only the COFOG code would be added.

2023-04-18 17:54 UTC, jpmckinney commented
I think it's fine to just add the COFOG code - unless adding both makes the mapping instructions simpler.

2023-04-18 21:27 UTC, duncandewhurst commented
@odscjen are you happy to make the changes discussed above?

2023-05-30 14:50 UTC, odscjen commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BT-10 (Activity Authority). BT-610 (Activity Entity), and BT-740 (Buyer Contracting Entity)](https://docs.ted.europa.eu/eforms/lat
Added that back in

2023-05-30 15:17 UTC, odscjen commented
Think I've applied the changes discussed, I've also updated the guidance to reflect using "eu-main-activity" rather than "Directive 2014/25/EU"

2023-06-07 04:08 UTC, duncandewhurst requested changes
Was there a reason for replacing 'EC' with 'EU' in the titles of the existing codes?

I think a further update is needed to `guidance.yaml` to use numeric COFOG codes per https://github.com/open-contracting-extensions/ocds_organizationClassification_extension/pull/4#issuecomment-1506047070

2023-06-09 14:29 UTC, odscjen commented
Just for consistency as the new codes descriptions reference the EU rather than the EC.

I've updated `guidance.yaml` for both BT-10 and BT-610 now

2023-06-14 02:25 UTC, duncandewhurst commented
`guidance.yaml` updates look good.

I'll leave it to @jpmckinney to decide on whether to replace 'EC' with 'EU' in the existing codes, as part of his review.

2023-06-15 05:15 UTC, jpmckinney commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BT-10 (Activity Authority). BT-610 (Activity Entity), and BT-740 (Buyer Contracting Entity)](https://docs.ted.europa.eu/eforms/lat
Let's remove the legal context. Organization classification is now commonly used for classifying women and minority-owned businesses, etc.

2023-06-15 05:15 UTC, jpmckinney commented on codelists/+itemClassificationScheme.csv
> +eu-main-activity,EU main activity authority list (eForms),The main activity of the contracting entity within the domain of public procurement according to the legislation of the European Parliament.
```suggestion
eu-main-activity,EU Main activity authority list (eForms),The main activity of the contracting entity within the domain of public procurement according to the legislation of the European Parliament. This scheme's codes match those in eForms.,https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/main-activity,organization
```

2023-06-15 05:15 UTC, jpmckinney commented on codelists/+itemClassificationScheme.csv
> +TED_CA_TYPE,EU Type of contracting authority,The types of contracting authority within the domain of public procurement according to legislation of the European Parliament.,https://simap.ted.europa.e
For consistency with the other TED code.

```suggestion
TED_CA_TYPE,EU Type of contracting authority (TED schema),The types of contracting authority within the domain of public procurement according to the legislation of the European Parliament. This scheme's codes match those in TED schema.,https://simap.ted.europa.eu/documents/10184/99173/EN_F01.pdf,organization
```

2023-06-15 05:15 UTC, jpmckinney commented on codelists/+itemClassificationScheme.csv
> +buyer-contracting-type,EU Buyer contracting entity type,Whether or not the buyer is a contracting entity within the domain of public procurement according to legislation of the European Parliament.,h
Probably needs the eu- prefix.

```suggestion
eu-buyer-contracting-type,EU Buyer contracting entity type,Whether or not the buyer is a contracting entity within the domain of public procurement according to the legislation of the European Parliament.,https://docs.ted.europa.eu/eforms/latest/reference/code-lists/buyer-contracting-type.html,organization
```

2023-06-15 05:15 UTC, jpmckinney commented on codelists/+itemClassificationScheme.csv
> +TED_CE_ACTIVITY,EU Main activity of contracting entity (TED schema),The main activities of contracting entities within the domain of public procurement according to legislation of the European Parlia
Align wording with new code.

```suggestion
TED_CE_ACTIVITY,EU Main activity of contracting entity (TED schema),The main activity of the contracting entity within the domain of public procurement according to the legislation of the European Parliament. This scheme's codes match those in TED schema.,https://simap.ted.europa.eu/documents/10184/99173/EN_F04.pdf,organization
```

2023-06-15 05:15 UTC, jpmckinney commented on README.md
> +* Add 'buyer-contracting-type' and 'Directive 2014/25/EU' to the `+itemClassificationScheme.csv` codelist.
Update to match added codes.

2023-06-15 05:17 UTC, jpmckinney commented
> properties within properties

This is just a warning not an error. It's a reminder to move nested properties into definitions, if appropriate.

2023-06-20 02:22 UTC, jpmckinney approved these changes

2023-06-20 02:22 UTC, merged